sudo: required
services:
  - docker

before_install:
  - docker build -t magnusfahlin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true magnusfahlin/react-test npm test

after_success:
  - docker build -t magnusfahlin/multi-client ./client
  - docker build -t magnusfahlin/multi-nginx ./nginx
  - docker build -t magnusfahlin/multi-server ./server
  - docker build -t magnusfahlin/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push magnusfahlin/multi-client
  - docker push magnusfahlin/multi-nginx
  - docker push magnusfahlin/multi-server
  - docker push magnusfahlin/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-909875351047
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
  secrets_access_key: $AWS_SECRET_KEY
